config/routes.rb
Hybrasyl::Application.routes.draw do

  root :to => 'ealagad#index'
  get '/contact' => 'ealagad#contact'
  get '/launcher' => 'ealagad#launcher'
  get '/about' => 'ealagad#about'
  get '/about/credits' => 'ealagad#credits'
  get '/releases' => 'ealagad#releases'
  get '/account/manager' => 'account#manager'
  get '/account/link' => 'account#link'
  get '/account/character/:id/reset' => 'account#reset'

  devise_for :accounts, ActiveAdmin::Devise.config.merge(path_names: { :sign_in => 'sign_in' })

  ActiveAdmin.routes(self)

  namespace :admin do
    get '/worldmaps/:id/pointeditor' => 'worldmaps#pointeditor'
  end

  namespace :api do
    namespace :v1 do
      post 'login/player', :to => "api#player_login"
      post 'login/account', :to => "api#account_login"
      get 'status', :to => "api#status"
    end
  end
end

app/controllers/application_controller.rb
#
# This file is part of Project Hybrasyl (Ealagad), a Rails interface to
# the Hybrasyl server.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the Affero General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# without ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the Affero General Public License
# for more details.
#
# You should have received a copy of the Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
#
# (C) 2013 Justin Baugh (baughj@hybrasyl.com)
# (C) 2015 Project Hybrasyl (info@hybrasyl.com)
#
# Authors:   Justin Baugh    <baughj@hybrasyl.com>
#

class ApplicationController < ActionController::Base
  layout :layout_by_resource
  protect_from_forgery

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html do
        redirect_to "/", :alert => exception.message
      end
    end
  end

  def current_ability
    @current_ability ||= Ability.new(current_account)
  end

  def after_sign_in_path_for(resource)
    if resource.is_a?(Account) 
      # Everyone should always go back to the main site after login
      "/"
    else
      super
    end
  end
end

app/helpers/application_helper.rb
#
# This file is part of Project Hybrasyl (Ealagad), a Rails interface to
# the Hybrasyl server.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the Affero General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# without ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the Affero General Public License
# for more details.
#
# You should have received a copy of the Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
#
# (C) 2013 Justin Baugh (baughj@hybrasyl.com)
# (C) 2015 Project Hybrasyl (info@hybrasyl.com)
#
# Authors:   Justin Baugh    <baughj@hybrasyl.com>
#

module ApplicationHelper
end

app/views/application/_banner.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
        <li class="pull-left brand">Project Hybrasyl</li>
      </ul>
    </div>
  </div>
</div>

app/views/application/_footer.html.erb
  <footer class="footer">
    <div class="container">
      <p>(C) 2013-2019 Project Hybrasyl. Generated by Ealagad, revision <code><%= HYBRASYL_REVISION %></code></p>
    </div>
 </footer>

app/views/application/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <li class="navbar-header">
      <a class="navbar-brand" href="/">Hybrasyl</a>
    </li>
    <ul class="nav navbar-nav">
      <li class="<%= request.fullpath == "/" ? "active" : "" %>"><a href="/">Project News</a></li>
      <li class="<%= request.fullpath == "/about" ? "active" : "" %>"><a href="/about">About</a></li>
      <li class="<%= request.fullpath == "/contact" ? "active" : "" %>"><a href="/contact">Contact Us</a></li>
      <li class=""><a href="https://github.com/hybrasyl">GitHub</a></li>
      <li class=""><a href="https://hybrasyl.atlassian.net">JIRA</a></li>
    </ul>

    <ul class="nav navbar-nav pull-right">
    <% if account_signed_in? %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_account.email %> <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a href="/account/manager">Account Manager</a></li>
        <li><%= link_to "Logout", "/accounts/sign_out", :method => :delete %></li>
        <% if current_account.can_access_admin? %>
        <li><a href="/admin">Admin Portal</a></li>
        <% end %>
      </ul>
    <% else %>
      <li><a href="/accounts/sign_in" class="<%= request.fullpath == "/accounts/sign_in" ? "active" : "" %>">Login</a></li>
      <li><a href="/accounts/sign_up" class="<%= request.fullpath == "/accounts/sign_up" ? "active" : "" %>">Create Account</a></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/application/_notices.html.erb
<div class="container">
  <% if flash.key? :notice %>
  <div class="alert alert-info alert-block">
    <button type="button" class="close" data-dismiss="alert">x</button>
    <%= flash[:notice] %>
  </div>
  <% elsif flash.key? :alert %>
  <div class="alert alert-error alert-block">
    <button type="button" class="close" data-dismiss="alert">x</button>
    <%= flash[:alert] %>
  </div>
  <% elsif flash.keys.count == 0 %>
    <%= devise_error_messages! %>
  <% end %>
</div>

app/views/application/pointeditor.erb
  <div><img id="toAnnotate" src="/assets/<%= @worldmap.client_map %>.png"></div>
  <script>
    $(window).load(function() {
      $("#toAnnotate").annotateImage({ editable:true, useAjax: true, worldmapId: <%= @worldmap.id %>});
    });
  </script>